FROM node:lts

WORKDIR /app
COPY package.json ./
RUN npm i --force 
COPY . .

ENV NODE_ENV=production
ENV BACKEND_URL=http://localhost:3001/api

RUN npm run build
EXPOSE 3000
CMD ["npm", "run", "start"]