FROM node:lts

WORKDIR /app
COPY ./frontend/package.json ./
COPY ./package-lock.json ./
RUN npm i --force 
COPY ./frontend/ .

ENV NODE_ENV=production
ENV BACKEND_URL=http://localhost:3001/api
ENV PORT=8000

RUN npm run build
EXPOSE 8000
CMD ["npm", "run", "start"]