/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  uuid,
  varchar,
  timestamp,
  boolean,
  numeric,
  integer,
  serial,
  jsonb,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'

export const company = pgTable(
  'company',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    company_name_idx: uniqueIndex('company_name_idx').on(columns.name),
    company_updated_at_idx: index('company_updated_at_idx').on(columns.updatedAt),
    company_created_at_idx: index('company_created_at_idx').on(columns.createdAt),
  }),
)

export const employment_type = pgTable(
  'employment_type',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    employment_type_name_idx: uniqueIndex('employment_type_name_idx').on(columns.name),
    employment_type_updated_at_idx: index('employment_type_updated_at_idx').on(columns.updatedAt),
    employment_type_created_at_idx: index('employment_type_created_at_idx').on(columns.createdAt),
  }),
)

export const experience = pgTable(
  'experience',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    title: varchar('title').notNull(),
    company: uuid('company_id')
      .notNull()
      .references(() => company.id, {
        onDelete: 'set null',
      }),
    employmentType: uuid('employment_type_id')
      .notNull()
      .references(() => employment_type.id, {
        onDelete: 'set null',
      }),
    startDate: timestamp('start_date', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
    isCurrentRole: boolean('is_current_role').notNull().default(false),
    endDate: timestamp('end_date', { mode: 'string', withTimezone: true, precision: 3 }),
    location: uuid('location_id').references(() => location.id, {
      onDelete: 'set null',
    }),
    workType: uuid('work_type_id').references(() => work_type.id, {
      onDelete: 'set null',
    }),
    description: varchar('description'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    experience_company_idx: index('experience_company_idx').on(columns.company),
    experience_employment_type_idx: index('experience_employment_type_idx').on(
      columns.employmentType,
    ),
    experience_location_idx: index('experience_location_idx').on(columns.location),
    experience_work_type_idx: index('experience_work_type_idx').on(columns.workType),
    experience_updated_at_idx: index('experience_updated_at_idx').on(columns.updatedAt),
    experience_created_at_idx: index('experience_created_at_idx').on(columns.createdAt),
  }),
)

export const location = pgTable(
  'location',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    location_name_idx: uniqueIndex('location_name_idx').on(columns.name),
    location_updated_at_idx: index('location_updated_at_idx').on(columns.updatedAt),
    location_created_at_idx: index('location_created_at_idx').on(columns.createdAt),
  }),
)

export const media = pgTable(
  'media',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize'),
    width: numeric('width'),
    height: numeric('height'),
    focalX: numeric('focal_x'),
    focalY: numeric('focal_y'),
  },
  (columns) => ({
    media_updated_at_idx: index('media_updated_at_idx').on(columns.updatedAt),
    media_created_at_idx: index('media_created_at_idx').on(columns.createdAt),
    media_filename_idx: uniqueIndex('media_filename_idx').on(columns.filename),
  }),
)

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: uuid('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => ({
    _orderIdx: index('users_sessions_order_idx').on(columns._order),
    _parentIDIdx: index('users_sessions_parent_id_idx').on(columns._parentID),
    _parentIDFk: foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  }),
)

export const users = pgTable(
  'users',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    loginAttempts: numeric('login_attempts').default('0'),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => ({
    users_updated_at_idx: index('users_updated_at_idx').on(columns.updatedAt),
    users_created_at_idx: index('users_created_at_idx').on(columns.createdAt),
    users_email_idx: uniqueIndex('users_email_idx').on(columns.email),
  }),
)

export const work_type = pgTable(
  'work_type',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    work_type_name_idx: uniqueIndex('work_type_name_idx').on(columns.name),
    work_type_updated_at_idx: index('work_type_updated_at_idx').on(columns.updatedAt),
    work_type_created_at_idx: index('work_type_created_at_idx').on(columns.createdAt),
  }),
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_locked_documents_global_slug_idx: index('payload_locked_documents_global_slug_idx').on(
      columns.globalSlug,
    ),
    payload_locked_documents_updated_at_idx: index('payload_locked_documents_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_locked_documents_created_at_idx: index('payload_locked_documents_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    companyID: uuid('company_id'),
    'employment-typeID': uuid('employment_type_id'),
    experienceID: uuid('experience_id'),
    locationID: uuid('location_id'),
    mediaID: uuid('media_id'),
    usersID: uuid('users_id'),
    'work-typeID': uuid('work_type_id'),
  },
  (columns) => ({
    order: index('payload_locked_documents_rels_order_idx').on(columns.order),
    parentIdx: index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_locked_documents_rels_path_idx').on(columns.path),
    payload_locked_documents_rels_company_id_idx: index(
      'payload_locked_documents_rels_company_id_idx',
    ).on(columns.companyID),
    payload_locked_documents_rels_employment_type_id_idx: index(
      'payload_locked_documents_rels_employment_type_id_idx',
    ).on(columns['employment-typeID']),
    payload_locked_documents_rels_experience_id_idx: index(
      'payload_locked_documents_rels_experience_id_idx',
    ).on(columns.experienceID),
    payload_locked_documents_rels_location_id_idx: index(
      'payload_locked_documents_rels_location_id_idx',
    ).on(columns.locationID),
    payload_locked_documents_rels_media_id_idx: index(
      'payload_locked_documents_rels_media_id_idx',
    ).on(columns.mediaID),
    payload_locked_documents_rels_users_id_idx: index(
      'payload_locked_documents_rels_users_id_idx',
    ).on(columns.usersID),
    payload_locked_documents_rels_work_type_id_idx: index(
      'payload_locked_documents_rels_work_type_id_idx',
    ).on(columns['work-typeID']),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    companyIdFk: foreignKey({
      columns: [columns['companyID']],
      foreignColumns: [company.id],
      name: 'payload_locked_documents_rels_company_fk',
    }).onDelete('cascade'),
    'employment-typeIdFk': foreignKey({
      columns: [columns['employment-typeID']],
      foreignColumns: [employment_type.id],
      name: 'payload_locked_documents_rels_employment_type_fk',
    }).onDelete('cascade'),
    experienceIdFk: foreignKey({
      columns: [columns['experienceID']],
      foreignColumns: [experience.id],
      name: 'payload_locked_documents_rels_experience_fk',
    }).onDelete('cascade'),
    locationIdFk: foreignKey({
      columns: [columns['locationID']],
      foreignColumns: [location.id],
      name: 'payload_locked_documents_rels_location_fk',
    }).onDelete('cascade'),
    mediaIdFk: foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    'work-typeIdFk': foreignKey({
      columns: [columns['work-typeID']],
      foreignColumns: [work_type.id],
      name: 'payload_locked_documents_rels_work_type_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_preferences_key_idx: index('payload_preferences_key_idx').on(columns.key),
    payload_preferences_updated_at_idx: index('payload_preferences_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_preferences_created_at_idx: index('payload_preferences_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: uuid('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: uuid('users_id'),
  },
  (columns) => ({
    order: index('payload_preferences_rels_order_idx').on(columns.order),
    parentIdx: index('payload_preferences_rels_parent_idx').on(columns.parent),
    pathIdx: index('payload_preferences_rels_path_idx').on(columns.path),
    payload_preferences_rels_users_id_idx: index('payload_preferences_rels_users_id_idx').on(
      columns.usersID,
    ),
    parentFk: foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    usersIdFk: foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  }),
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: uuid('id').defaultRandom().primaryKey(),
    name: varchar('name'),
    batch: numeric('batch'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => ({
    payload_migrations_updated_at_idx: index('payload_migrations_updated_at_idx').on(
      columns.updatedAt,
    ),
    payload_migrations_created_at_idx: index('payload_migrations_created_at_idx').on(
      columns.createdAt,
    ),
  }),
)

export const relations_company = relations(company, () => ({}))
export const relations_employment_type = relations(employment_type, () => ({}))
export const relations_experience = relations(experience, ({ one }) => ({
  company: one(company, {
    fields: [experience.company],
    references: [company.id],
    relationName: 'company',
  }),
  employmentType: one(employment_type, {
    fields: [experience.employmentType],
    references: [employment_type.id],
    relationName: 'employmentType',
  }),
  location: one(location, {
    fields: [experience.location],
    references: [location.id],
    relationName: 'location',
  }),
  workType: one(work_type, {
    fields: [experience.workType],
    references: [work_type.id],
    relationName: 'workType',
  }),
}))
export const relations_location = relations(location, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_work_type = relations(work_type, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    companyID: one(company, {
      fields: [payload_locked_documents_rels.companyID],
      references: [company.id],
      relationName: 'company',
    }),
    'employment-typeID': one(employment_type, {
      fields: [payload_locked_documents_rels['employment-typeID']],
      references: [employment_type.id],
      relationName: 'employment-type',
    }),
    experienceID: one(experience, {
      fields: [payload_locked_documents_rels.experienceID],
      references: [experience.id],
      relationName: 'experience',
    }),
    locationID: one(location, {
      fields: [payload_locked_documents_rels.locationID],
      references: [location.id],
      relationName: 'location',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    'work-typeID': one(work_type, {
      fields: [payload_locked_documents_rels['work-typeID']],
      references: [work_type.id],
      relationName: 'work-type',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  company: typeof company
  employment_type: typeof employment_type
  experience: typeof experience
  location: typeof location
  media: typeof media
  users_sessions: typeof users_sessions
  users: typeof users
  work_type: typeof work_type
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_company: typeof relations_company
  relations_employment_type: typeof relations_employment_type
  relations_experience: typeof relations_experience
  relations_location: typeof relations_location
  relations_media: typeof relations_media
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_work_type: typeof relations_work_type
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
